name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew

    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew clean build -x test

    - name: Create deployment package
      run: |
        cd backend
        python3 create_deployment_package.py

    - name: Get timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: kiosk-backend
        environment_name: Kiosk-backend-env
        version_label: backend-github-${{ steps.timestamp.outputs.timestamp }}
        region: ap-northeast-2
        deployment_package: backend/backend-unix-zip.zip
        wait_for_deployment: true
