# Local Development Environment (localhost MySQL)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kioskdb
    username: root
    password: aioztesting
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: false

logging:
  level:
    com.kiosk.backend: DEBUG
    org.springframework.security: DEBUG
