name: Test GitHub Secrets

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-secrets.yml'

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if secrets exist
      run: |
        echo "Checking GitHub Secrets availability..."

        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          echo "❌ AWS_ACCESS_KEY_ID is EMPTY or NOT SET"
        else
          echo "✅ AWS_ACCESS_KEY_ID is SET (length: ${#AWS_ACCESS_KEY_ID})"
        fi

        if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
          echo "❌ AWS_SECRET_ACCESS_KEY is EMPTY or NOT SET"
        else
          echo "✅ AWS_SECRET_ACCESS_KEY is SET (length: ${#AWS_SECRET_KEY})"
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Test AWS credentials (if secrets exist)
      if: ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != '' }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Verify AWS connection
      if: ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != '' }}
      run: |
        echo "Testing AWS CLI access..."
        aws sts get-caller-identity || echo "AWS authentication failed"

    - name: Instructions if secrets not found
      if: ${{ secrets.AWS_ACCESS_KEY_ID == '' || secrets.AWS_SECRET_ACCESS_KEY == '' }}
      run: |
        echo ""
        echo "========================================="
        echo "GitHub Secrets가 감지되지 않았습니다!"
        echo "========================================="
        echo ""
        echo "설정 방법:"
        echo "1. GitHub 저장소 페이지로 이동"
        echo "2. Settings 탭 클릭"
        echo "3. 왼쪽 메뉴에서 'Secrets and variables' → 'Actions' 클릭"
        echo "4. 'Repository secrets' 섹션 확인 (Environment secrets 아님!)"
        echo "5. 'New repository secret' 버튼으로 추가:"
        echo "   - Name: AWS_ACCESS_KEY_ID"
        echo "   - Value: 실제 AWS Access Key"
        echo "   - Name: AWS_SECRET_ACCESS_KEY"
        echo "   - Value: 실제 AWS Secret Key"
        echo ""
        echo "주의사항:"
        echo "- Secret 이름은 정확히 일치해야 합니다 (대소문자 구분)"
        echo "- 앞뒤 공백이 없어야 합니다"
        echo "- 'Environment secrets'가 아닌 'Repository secrets'에 추가"
        echo ""
        exit 1
