name: Test GitHub Secrets

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-secrets.yml'

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if secrets exist
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "Checking GitHub Secrets availability..."
        echo ""

        SECRET_STATUS=0

        if [ -z "$AWS_ACCESS_KEY_ID" ]; then
          echo "❌ AWS_ACCESS_KEY_ID is EMPTY or NOT SET"
          SECRET_STATUS=1
        else
          KEY_LENGTH=${#AWS_ACCESS_KEY_ID}
          echo "✅ AWS_ACCESS_KEY_ID is SET (length: $KEY_LENGTH)"
        fi

        if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "❌ AWS_SECRET_ACCESS_KEY is EMPTY or NOT SET"
          SECRET_STATUS=1
        else
          SECRET_LENGTH=${#AWS_SECRET_ACCESS_KEY}
          echo "✅ AWS_SECRET_ACCESS_KEY is SET (length: $SECRET_LENGTH)"
        fi

        echo ""
        if [ $SECRET_STATUS -eq 1 ]; then
          echo "=========================================  "
          echo "GitHub Secrets가 감지되지 않았습니다!"
          echo "========================================="
          echo ""
          echo "설정 방법:"
          echo "1. GitHub 저장소 페이지로 이동"
          echo "2. Settings 탭 클릭"
          echo "3. 왼쪽 메뉴에서 'Secrets and variables' → 'Actions' 클릭"
          echo "4. 'Repository secrets' 섹션 확인 (Environment secrets 아님!)"
          echo "5. 'New repository secret' 버튼으로 추가:"
          echo "   - Name: AWS_ACCESS_KEY_ID"
          echo "   - Value: 실제 AWS Access Key"
          echo "   - Name: AWS_SECRET_ACCESS_KEY"
          echo "   - Value: 실제 AWS Secret Key"
          echo ""
          echo "주의사항:"
          echo "- Secret 이름은 정확히 일치해야 합니다 (대소문자 구분)"
          echo "- 앞뒤 공백이 없어야 합니다"
          echo "- 'Environment secrets'가 아닌 'Repository secrets'에 추가"
          echo ""
          exit 1
        fi

    - name: Configure AWS credentials
      if: success()
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Verify AWS connection
      if: success()
      run: |
        echo ""
        echo "========================================="
        echo "Testing AWS CLI access..."
        echo "========================================="
        echo ""

        if aws sts get-caller-identity; then
          echo ""
          echo "========================================="
          echo "✅ AWS 인증 성공!"
          echo "========================================="
          echo ""
          echo "GitHub Secrets가 올바르게 설정되었습니다."
          echo "이제 자동 배포를 사용할 수 있습니다!"
          echo ""
        else
          echo ""
          echo "========================================="
          echo "❌ AWS 인증 실패"
          echo "========================================="
          echo ""
          echo "Secrets는 설정되었지만 유효하지 않은 키입니다."
          echo "AWS Console에서 새 Access Key를 발급받으세요."
          echo ""
          exit 1
        fi
